server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
jwt:
  secret: super_secret_key_123